// examples/src/examples/r2v/basic/counter.tsx
import { useState } from 'react';
export default function Counter({
  defaultCount = 0,
  className,
  style,
}: {
  defaultCount?: number;
} & React.HTMLAttributes<HTMLDivElement>) {
  const [count, setCount] = useState(defaultCount);
  return (
    <div className={className} style={style}>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}

// examples/src/examples/v2r/basic/counter.vue
<script setup lang="ts">
import { ref } from 'vue';

interface Props {
  defaultCount?: number;
}
const props = withDefaults(defineProps<Props>(), {
  defaultCount: 0,
});

const count = ref(props.defaultCount);

function onClick() {
  count.value++;
}
</script>

<template>
  <div>
    <p>You clicked {{ count }} times</p>
    <button @click="onClick">Click me</button>
  </div>
</template>
