// examples/src/examples/v2r/react-context/example.tsx
/**
 * React 向 Vue 组件传递 React context
 */
import { v2r } from 'vuact';
import { useState } from 'react';
import Counter from './counter.vue';
import { CounterContext } from './context';

const RCounter = v2r(Counter);

export default function Example() {
  const [context, setContext] = useState({
    count: 1,
    setCount,
  });
  function setCount(count: number) {
    setContext({
      ...context,
      count,
    });
  }

  return (
    <CounterContext.Provider value={context}>
      <RCounter defaultCount={1} />
    </CounterContext.Provider>
  );
}

// examples/src/examples/v2r/vue-context/example.tsx
/**
 * React 向 Vue 组件传递 Vue context
 */
import { v2r, VueContextProvider } from 'vuact';
import { useMemo } from 'react';
import { shallowRef } from 'vue';
import Counter from './counter.vue';
import { type CounterContext, counterInjectionKey } from './context';

const RCounter = v2r(Counter);

export default function Example() {
  const counterContext = useMemo(() => {
    const count = shallowRef(1);
    return {
      count,
      setCount: (c) => {
        count.value = c;
      },
    } as CounterContext;
  }, []);

  return (
    // 按 Vue 规范，Vue context 不能改变，所以 VueContextProvider 的 value 不允许改变
    <VueContextProvider contextKey={counterInjectionKey} value={counterContext}>
      <RCounter defaultCount={1} />
    </VueContextProvider>
  );
}
