// examples/src/examples/v2r/vue-context/counter.vue
<script setup lang="ts">
import { inject } from 'vue';
import { counterInjectionKey } from './context';

const counterContext = inject(counterInjectionKey)!;
const { count } = counterContext;

function onClick() {
  counterContext.setCount(count.value + 1);
}
</script>

<template>
  <div>
    <p>You clicked {{ count }} times</p>
    <button @click="onClick">Click me</button>
  </div>
</template>

// examples/src/examples/r2v/react-context/counter.tsx
import { createContext, useContext } from 'react';

export const CounterContext = createContext({
  count: 0,
  setCount: (count: number) => {},
});

export default function Counter() {
  // 获取 vue 组件传递过来的 context
  const { count, setCount } = useContext(CounterContext);
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}
