// examples/src/examples/r2v/vue-context/counter.tsx
import { inject } from 'vue';
import { counterInjectionKey } from './context';

export default function Counter() {
  // react 组件内可以直接调用 vue 的 inject 获取 vue context
  const context = inject(counterInjectionKey)!;
  return (
    <div>
      <p>You clicked {context.count.value} times</p>
      <button onClick={() => context.setCount(context.count.value + 1)}>
        Click me
      </button>
    </div>
  );
}

// examples/src/examples/r2v/react-context/counter.tsx
import { createContext, useContext } from 'react';

export const CounterContext = createContext({
  count: 0,
  setCount: (count: number) => {},
});

export default function Counter() {
  // 获取 vue 组件传递过来的 context
  const { count, setCount } = useContext(CounterContext);
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}
