// examples/src/examples/v2r/react-context/counter.vue
<script setup lang="ts">
import { injectContext } from 'vuact';
import { CounterContext } from './context';

// 使用 injectContext 在 vue 组件中获取 react 的 context，获取到的 context 是原始 context 值的 shallowRef
const counterContextRef = injectContext(CounterContext);

function onClick() {
  counterContextRef.value.setCount(counterContextRef.value.count + 1);
}
</script>

<template>
  <div>
    <p>You clicked {{ counterContextRef.count }} times</p>
    <button @click="onClick">Click me</button>
  </div>
</template>

// examples/src/examples/r2v/react-context/counter.tsx
import { createContext, useContext } from 'react';

export const CounterContext = createContext({
  count: 0,
  setCount: (count: number) => {},
});

export default function Counter() {
  // 获取 vue 组件传递过来的 context
  const { count, setCount } = useContext(CounterContext);
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}
