// examples/src/examples/r2v/vue-context/counter.tsx
import { inject } from 'vue';
import { counterInjectionKey } from './context';

export default function Counter() {
  // react 组件内可以直接调用 vue 的 inject 获取 vue context
  const context = inject(counterInjectionKey)!;
  return (
    <div>
      <p>You clicked {context.count.value} times</p>
      <button onClick={() => context.setCount(context.count.value + 1)}>
        Click me
      </button>
    </div>
  );
}

// examples/src/examples/r2v/basic/counter.tsx
import { useState } from 'react';
export default function Counter({
  defaultCount = 0,
  className,
  style,
}: {
  defaultCount?: number;
} & React.HTMLAttributes<HTMLDivElement>) {
  const [count, setCount] = useState(defaultCount);
  return (
    <div className={className} style={style}>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}
