// examples/src/examples/v2r/basic/example.tsx
/**
 * React 调 Vue 组件基本用法
 */
import { v2r } from 'vuact';
import Counter from './counter.vue';

// Vue 组件转为 React 组件
const RCounter = v2r(Counter);

export default function Example() {
  // class 与 style 可按 react 规范传递
  // 传递给 Vue 组件之后 className 会被转为 class，style object 中 Unitless 样式会自动加上单位
  // 比如 height: 100 => height: '100px'
  return (
    <RCounter defaultCount={1} className="counter" style={{ height: 100 }} />
  );
}

// examples/src/examples/r2v/basic/example.vue
<script setup lang="ts">
/**
 * Vue 调用 React 组件基本用法
 */
import { r2v } from 'vuact';
import Counter from './counter.tsx';

// React 组件转为 Vue 组件
const VCounter = r2v(Counter);
</script>
<template>
  <!-- class style 属性可按 vue 规范传递，传递给 React 组件之后 class 会被转为 className，style 会被转为 object -->
  <VCounter :defaultCount="1" class="counter" style="border: 1px solid #ddd" />
</template>
