// examples/src/examples/r2v/event/counter.tsx
import { useState } from 'react';
export default function Counter({
  count,
  onUpdateCount,
}: {
  count?: number;
  onUpdateCount?: (count: number) => void;
}) {
  const [_count, setCount] = useState(0);
  const finalCount = count ?? _count;

  function onIncrement() {
    setCount(finalCount + 1);
    onUpdateCount?.(finalCount + 1);
  }
  return (
    <div>
      <p>You clicked {finalCount} times</p>
      <button onClick={onIncrement}>Click me</button>
    </div>
  );
}

// examples/src/examples/r2v/vue-context/counter.tsx
import { inject } from 'vue';
import { counterInjectionKey } from './context';

export default function Counter() {
  // react 组件内可以直接调用 vue 的 inject 获取 vue context
  const context = inject(counterInjectionKey)!;
  return (
    <div>
      <p>You clicked {context.count.value} times</p>
      <button onClick={() => context.setCount(context.count.value + 1)}>
        Click me
      </button>
    </div>
  );
}
