// examples/src/examples/r2v/react-context/example.vue.tsx
import { defineComponent, shallowRef } from 'vue';
import { provideContext, r2v } from 'vuact';
import Counter, { CounterContext } from './counter';

const VCounter = r2v(Counter);

export default defineComponent({
  setup: () => {
    function setCount(count: number) {
      counterContextRef.value = {
        ...counterContextRef.value,
        count,
      };
    }

    const counterContextRef = shallowRef({
      count: 1,
      setCount,
    });

    provideContext(CounterContext, counterContextRef);

    return () => {
      return <VCounter />;
    };
  },
});

// examples/src/examples/v2r/react-context/example.tsx
/**
 * React 向 Vue 组件传递 React context
 */
import { v2r } from 'vuact';
import { useState } from 'react';
import Counter from './counter.vue';
import { CounterContext } from './context';

const RCounter = v2r(Counter);

export default function Example() {
  const [context, setContext] = useState({
    count: 1,
    setCount,
  });
  function setCount(count: number) {
    setContext({
      ...context,
      count,
    });
  }

  return (
    <CounterContext.Provider value={context}>
      <RCounter defaultCount={1} />
    </CounterContext.Provider>
  );
}
